#!/bin/bash
matlab="matlab -nodesktop -nosplash"
# average distance
$matlab <<< "xint=1; xp=5; model='avedist' ; qgrantham=1 ; maxiter=4000 ; sdstep=0.015 ;  nptype='admix'; allagsplit ; show ; exit" >& mkfigS2c.out
$matlab <<< "xint=1; xp=5; model='avedist' ; qgrantham=1 ; maxiter=4000 ; sdstep=0.015 ;  nptype='admix'; allvacsplit ; qvacsplit=1 ; lbl='\itD' show ; exit" >& mkfigS2c-rev.out
