#!/bin/bash
matlab="matlab -nodesktop -nosplash"
# distance to average
#$matlab <<< "xint=1; xp=2.5; model='dist2ave' ; Diff=0.3 ;  allagsplit ; qvacsplit=0; show ; trains={'sars-2'} ; show ;  exit " >& mkfig5c.out
#$matlab <<< "xint=1; xp=2.5; model='dist2ave' ; Diff=0.3 ;  allvacsplit ; qvacsplit=1; show ;  exit "  >& mkfig5c-rev.out
